export const prodHomecompData = [
  {
    id: "air-canvas",
    href1: "/",
    src1: "/assets/images/prodImages/airCanvas/homePage/canvas1.webp",
    alt1: "Air Canvas Vest",
    href2: "/",
    src2: "/assets/images/prodImages/airCanvas/homePage/canvas2.webp",
    alt2: "Air Canvas Vest",
    href3: "/",
    src3: "/assets/images/prodImages/airCanvas/homePage/canvasMob.webp",
    alt3: "Air Canvas Vest",
    schematicsrc: "/assets/images/schematics/vestSchema.svg",
    schematicalt: "Vest Schematics",
    width: 600,
    height: 0,
    slides: [
      "/assets/images/prodImages/airCanvas/homePage/carousel/carCanvas1.webp",
      "/assets/images/prodImages/airCanvas/homePage/carousel/carCanvas2.webp",
      "/assets/images/prodImages/airCanvas/homePage/carousel/carCanvas3.webp",
    ],
    productName: "VR: AIR CANVAS",
    productDesc:
      "Imagine, a returning astronaut coming home to a new world. The VR Air Canvas encompasses an astronaut styled off white canvas puffer with direct openings for sensor placement. Equipped with an environmental carbon sensor, VR Air Canvas offers a glimpse into the world around us. Accurate readings of indoor and outdoor environments provide invaluable insights, allowing you to navigate and connect with your surroundings like never before. Designed to adapt to individual preferences, it can be worn with or without compatible sensors, showcasing the exploration of heavy-duty cotton and its harmonious aging abilities alongside its integrated parts.",
    productDesc2:
      "Imagine, a returning astronaut coming home to a new world. The VR Air Canvas encompasses an astronaut styled off white canvas puffer with direct openings for sensor placement. Equipped with an environmental carbon sensor, VR Air Canvas offers a glimpse into.....",
  },
  {
    id: "air-explorer",
    href1: "/",
    src1: "/assets/images/prodImages/airExplorer/homePage/explorer1.webp",
    alt1: "Air Explorer Vest",
    href2: "/",
    src2: "/assets/images/prodImages/airExplorer/homePage/explorer2.webp",
    alt2: "Air explorer Vest",
    href3: "/",
    src3: "/assets/images/prodImages/airExplorer/homePage/explorerMob.webp",
    alt3: "Air Explorer Vest",
    schematicsrc: "/assets/images/schematics/vestSchema.svg",
    schematicalt: "Vest Schematics",
    width: 600,
    height: 0,  
    slides: [
      "/assets/images/prodImages/airExplorer/homePage/carousel/carExplorer1.webp",
      "/assets/images/prodImages/airExplorer/homePage/explorer1.webp",
      "/assets/images/prodImages/airExplorer/homePage/explorer2.webp",
    ],
    productName: "VR: AIR EXPLORER",
    productDesc:
      "Explore where no one else has, like no one else has with the VR Air Explorer. Users are able to enjoy comfort alongside ample storage space. The Explorer features a unique blend of nylon and suede. This device was designed for specialty sensors that may be bigger in size or require a bigger storage as well as external access making installation a lot easier. Install and begin your journey.",
    productDesc2:
      "Explore where no one else has, like no one else has with the VR Air Explorer. Users are able to enjoy comfort alongside ample storage space. The Explorer features a unique blend of nylon and suede. This device was designed for specialty  .....",
  },
  {
    id: "air-bubbleBlack",
    href1: "/",
    src1: "/assets/images/prodImages/bubbleBlack/homePage/bubbleBlack1.webp",
    alt1: "Air Bubble Black Vest",
    href2: "/",
    src2: "/assets/images/prodImages/bubbleBlack/homePage/bubbleBlack2.webp",
    alt2: "Air Bubble Black Vest",
    href3: "/",
    src3: "/assets/images/prodImages/bubbleBlack/homePage/bubbleBlackMob.webp",
    alt3: "Air Bubble Black Vest",
    schematicsrc: "/assets/images/schematics/vestSchema.svg",
    schematicalt: "Vest Schematics",
    width: 600,
    height: 0,  
    slides: [
      "/assets/images/prodImages/bubbleBlack/homePage/carousel/carBubbleBlack1.webp",
      "/assets/images/prodImages/bubbleBlack/homePage/carousel/carBubbleBlack2.webp",
      "/assets/images/prodImages/bubbleBlack/homePage/carousel/carBubbleBlack3.webp",
    ],
    productName: "VR: AIR BUBBLE BLACK",
    productDesc:
      "This device was original designed to house VR technologies and can accommodate other wearable technologies, with its access pockets and wire conduits, allowing users with the possibility of testing out their own ideas. The VR Air Vest comes equipped with an environmental carbon sensor allowing users to get accurate indoor and outdoor readings.",
    productDesc2:
      "This device was original designed to house VR technologies and can accommodate other wearable technologies, with its access pockets and wire conduits, allowing users with the possibility of testing out their own ideas  ......",
  },
  {
    id: "air-carbon",
    href1: "/",
    src1: "/assets/images/prodImages/airCarbon/homePage/carbon1.webp",
    alt1: "Air Carbon Vest",
    href2: "/",
    src2: "/assets/images/prodImages/airCarbon/homePage/carbon2.webp",
    alt2: "Air Carbon Vest",
    href3: "/",
    src3: "/assets/images/prodImages/airCarbon/homePage/carbonMob.webp",
    alt3: "Air Carbon Vest",
    schematicsrc: "/assets/images/schematics/vestSchema.svg",
    schematicalt: "Vest Schematics",
    width: 600,
    height: 0,  
    slides: [
      "/assets/images/prodImages/airCarbon/homePage/carousel/carCarbon1.webp",
      "/assets/images/prodImages/airCarbon/homePage/carousel/carCarbon2.webp",
      "/assets/images/prodImages/airCarbon/homePage/carousel/carCarbon3.webp",
      "/assets/images/prodImages/airCarbon/homePage/carousel/carCarbon4.webp",
    ],
    productName: "VR: AIR CARBON",
    productDesc:
      "The VR Air Carbon explores materiality in a whole new way. The effects of carbon on the environment is becoming more and more prevalent with each day. Environmental awareness is woven into the fabric- the patina-like texture Is more symbolic than it is functional representing the oxidation of carbon steel, a reminder that time is running out. Armed with real-time data and insights, you have the power to make informed decisions that benefit both yourself and the planet. From reducing indoor pollutants to advocating for cleaner air initiatives, every action you take makes a difference and you are reminded of this with each step.",
    productDesc2:
      "The VR Air Carbon explores materiality in a whole new way. The effects of carbon on the environment is becoming more and more prevalent with each day. Environmental awareness is woven into the fabric- the patina-like texture   ......",
  },
  {
    id: "themal-pants",
    href1: "/",
    src1: "/assets/images/prodImages/thermalPants/homePage/pants1.webp",
    alt1: "Air Thermal Pants",
    href2: "/",
    src2: "/assets/images/prodImages/thermalPants/homePage/pants2.webp",
    alt2: "Air Thermal Pants",
    href3: "/",
    src3: "/assets/images/prodImages/thermalPants/homePage/pantsMob.webp",
    alt3: "Air Thermal Pants",
    schematicsrc: "/assets/images/schematics/pantsSchema.png",
    schematicalt: "Pants Schematics",
    width: 1100,
    height: 0,  
    slides: [
      "/assets/images/prodImages/thermalPants/homePage/carousel/carPants1.webp",
      "/assets/images/prodImages/thermalPants/homePage/carousel/carPants2.webp",
      "/assets/images/prodImages/thermalPants/homePage/carousel/carPants3.webp",
      "/assets/images/prodImages/thermalPants/homePage/carousel/carPants4.webp",
    ],
    productName: "VR: THERMAL PANTS",
    productDesc:
      "Whether you're trekking through the wilderness or navigating the urban jungle, the VR Prototype Pants are your ultimate companion for long-distance travel. With the ability to monitor shifting environmental temperatures on the go, you can adapt and adjust your journey with ease, ensuring a seamless and comfortable experience from start to finish. Environmental temperature information is right at your fingertips. Seamlessly integrated LED lights embedded into the fabric provide real-time temperature readings, allowing you to stay informed and connected no matter where your adventures take you. Simply glance down and let the subtle colors guide you, eliminating the need for additional devices or distractions. Whether you're a seasoned explorer or simply seeking new experiences, these pants empower you to connect with your environment, adapt to changing conditions, and embrace the journey with confidence and style. So go ahead, step into a new terrain, and let your adventures begin.",
    productDesc2:
      "Whether you're trekking through the wilderness or navigating the urban jungle, the VR Prototype Pants are your ultimate companion for long-distance travel. With the ability to monitor shifting environmental temperatures on the go ......",
  },  
  // {
  //   id: "pants-section",
  //   href1: "/",
  //   src1: "/assets/images/air-explorer/section-1/ae-sec-1-1.webp",
  //   alt1: "test",
  //   href2: "/",
  //   src2: "/assets/images/air-explorer/section-1/ae-sec-1-2.webp",
  //   alt2: "test2",
  //   schematicsrc: "/assets/images/vest-schema1.svg",
  //   schematicalt: "test",
  //   width: 600,
  //   height: 500,
  //   slides: [
  //     "/assets/images/air-explorer/section-1/ae-sec-1-5.webp",
  //     "/assets/images/air-explorer/section-1/ae-sec-1-3.webp",
  //     "/assets/images/air-explorer/section-1/ae-sec-1-4.webp",
  //   ],
  //   productName: "VR: THERMAL PANTS",
  //   productDesc:
  //     "Whether you're trekking through the wilderness or navigating the urban jungle, the VR Prototype Pants are your ultimate companion for long-distance travel. With the ability to monitor shifting environmental temperatures on the go, you can adapt and adjust your journey with ease, ensuring a seamless and comfortable experience from start to finish. Environmental temperature information is right at your fingertips. Seamlessly integrated LED lights embedded into the fabric provide real-time temperature readings, allowing you to stay informed and connected no matter where your adventures take you. Simply glance down and let the subtle colors guide you, eliminating the need for additional devices or distractions. Whether you're a seasoned explorer or simply seeking new experiences, these pants empower you to connect with your environment, adapt to changing conditions, and embrace the journey with confidence and style. So go ahead, step into a new terrain, and let your adventures begin.",
  // },
];
